from Bio import AlignIO, Phylo
import subprocess                
import matplotlib.pyplot as plt  
import os                        

def convert_fasta_to_phylip(fasta_path, phylip_path):
    """
    Convert a sequence alignment from FASTA to PHYLIP-relaxed format.
    PHYLIP-relaxed allows longer sequence names and is accepted by PhyML.
    """
    #Read the alignment in FASTA format
    alignment = AlignIO.read(fasta_path, "fasta-pearson")
    #Write the alignment in PHYLIP-relaxed format
    AlignIO.write(alignment, phylip_path, "phylip-relaxed")

def run_phyml(phylip_path):
    """
    Run PhyML using the PHYLIP alignment file.
    The parameter -b 100 specifies that 100 bootstrap replicates should be performed.
    """
    cmd = ["phyml", "-i", phylip_path, "-d", "nt", "-b", "100"]
    subprocess.run(cmd, check=True)

def visualize_tree(tree_file):
    """
    Read the phylogenetic tree generated by PhyML (in Newick format)
    and display it.
    """
    tree = Phylo.read(tree_file, "newick")
    Phylo.draw(tree)

def main():
    """
    1. Convert FASTA alignment to PHYLIP format
    2. Run PhyML to infer a phylogenetic tree
    3. Visualize the resulting tree
    """
  
    fasta_path = "/home/barbara/documents/RegPatternSearch/16S_alinhadas_principaisgenomas/aligned_sequences10.fasta"
    phylip_path = "/home/barbara/documents/RegPatternSearch/16S_alinhadas_principaisgenomas/aligned_sequences_10.phy"
    
    print("Converting to PHYLIP...")
    convert_fasta_to_phylip(fasta_path, phylip_path)

    print("Running PhyML...")
    run_phyml(phylip_path)

    #PhyML typically outputs a tree file with this suffix format
    tree_file = phylip_path + "_phyml_10_tree.txt"

    #Check if the tree file was created successfully
    if os.path.exists(tree_file):
        print("Displaying tree")
        visualize_tree(tree_file)
    else:
        print(f"Tree file not found: {tree_file}")

#Run the script when executed directly
if __name__ == "__main__":
    main()
